// GENERATED by the Supabase MCP generate_typescript_types tool — do not edit.
// Regenerate after every migration (docs/MODULES.md step 9).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_events: {
        Row: {
          action: string
          actor: string | null
          at: string
          diff: Json | null
          id: number
          row_id: string | null
          table_name: string
          tenant_id: string
        }
        Insert: {
          action: string
          actor?: string | null
          at?: string
          diff?: Json | null
          id?: never
          row_id?: string | null
          table_name: string
          tenant_id: string
        }
        Update: {
          action?: string
          actor?: string | null
          at?: string
          diff?: Json | null
          id?: never
          row_id?: string | null
          table_name?: string
          tenant_id?: string
        }
        Relationships: []
      }
      contacts: {
        Row: {
          created_at: string
          created_by: string | null
          customer_id: string
          department: string | null
          email: string | null
          id: string
          is_primary: boolean
          name: string
          notes: string | null
          phone: string | null
          tenant_id: string
          title: string | null
          updated_at: string
          updated_by: string | null
          whatsapp: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          customer_id: string
          department?: string | null
          email?: string | null
          id?: string
          is_primary?: boolean
          name: string
          notes?: string | null
          phone?: string | null
          tenant_id?: string
          title?: string | null
          updated_at?: string
          updated_by?: string | null
          whatsapp?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          customer_id?: string
          department?: string | null
          email?: string | null
          id?: string
          is_primary?: boolean
          name?: string
          notes?: string | null
          phone?: string | null
          tenant_id?: string
          title?: string | null
          updated_at?: string
          updated_by?: string | null
          whatsapp?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contacts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sl_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          address: string | null
          billing_terms: string | null
          city: string | null
          country: string | null
          cr_number: string | null
          created_at: string
          created_by: string | null
          credit_limit: number | null
          email: string | null
          id: string
          name: string
          notes: string | null
          phone: string | null
          status: string
          tax_number: string | null
          tenant_id: string
          updated_at: string
          updated_by: string | null
          website: string | null
        }
        Insert: {
          address?: string | null
          billing_terms?: string | null
          city?: string | null
          country?: string | null
          cr_number?: string | null
          created_at?: string
          created_by?: string | null
          credit_limit?: number | null
          email?: string | null
          id?: string
          name: string
          notes?: string | null
          phone?: string | null
          status?: string
          tax_number?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          website?: string | null
        }
        Update: {
          address?: string | null
          billing_terms?: string | null
          city?: string | null
          country?: string | null
          cr_number?: string | null
          created_at?: string
          created_by?: string | null
          credit_limit?: number | null
          email?: string | null
          id?: string
          name?: string
          notes?: string | null
          phone?: string | null
          status?: string
          tax_number?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      document_sequences: {
        Row: {
          doc_type: string
          next_number: number
          tenant_id: string
        }
        Insert: {
          doc_type: string
          next_number?: number
          tenant_id: string
        }
        Update: {
          doc_type?: string
          next_number?: number
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "document_sequences_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      drivers: {
        Row: {
          created_at: string
          created_by: string | null
          email: string | null
          first_name: string
          hire_date: string | null
          id: string
          last_name: string
          license_class: string | null
          license_expiry: string | null
          license_number: string | null
          notes: string | null
          phone: string | null
          status: string
          tenant_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          email?: string | null
          first_name: string
          hire_date?: string | null
          id?: string
          last_name?: string
          license_class?: string | null
          license_expiry?: string | null
          license_number?: string | null
          notes?: string | null
          phone?: string | null
          status?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          email?: string | null
          first_name?: string
          hire_date?: string | null
          id?: string
          last_name?: string
          license_class?: string | null
          license_expiry?: string | null
          license_number?: string | null
          notes?: string | null
          phone?: string | null
          status?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "drivers_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      fuel_logs: {
        Row: {
          created_at: string
          created_by: string | null
          driver_id: string | null
          filled_at: string
          id: string
          is_full_tank: boolean
          notes: string | null
          odometer: number | null
          tenant_id: string
          total_cost: number
          updated_by: string | null
          vehicle_id: string
          vendor: string | null
          volume: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          driver_id?: string | null
          filled_at?: string
          id?: string
          is_full_tank?: boolean
          notes?: string | null
          odometer?: number | null
          tenant_id?: string
          total_cost?: number
          updated_by?: string | null
          vehicle_id: string
          vendor?: string | null
          volume: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          driver_id?: string | null
          filled_at?: string
          id?: string
          is_full_tank?: boolean
          notes?: string | null
          odometer?: number | null
          tenant_id?: string
          total_cost?: number
          updated_by?: string | null
          vehicle_id?: string
          vendor?: string | null
          volume?: number
        }
        Relationships: [
          {
            foreignKeyName: "fuel_logs_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fuel_logs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fuel_logs_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      inspection_templates: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          id: string
          items: Json
          name: string
          tenant_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          id?: string
          items?: Json
          name: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          id?: string
          items?: Json
          name?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inspection_templates_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      inspections: {
        Row: {
          created_at: string
          created_by: string | null
          driver_id: string | null
          id: string
          notes: string | null
          odometer: number | null
          performed_at: string
          results: Json
          status: string
          template_id: string | null
          tenant_id: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          driver_id?: string | null
          id?: string
          notes?: string | null
          odometer?: number | null
          performed_at?: string
          results?: Json
          status?: string
          template_id?: string | null
          tenant_id?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          driver_id?: string | null
          id?: string
          notes?: string | null
          odometer?: number | null
          performed_at?: string
          results?: Json
          status?: string
          template_id?: string | null
          tenant_id?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inspections_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspections_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "inspection_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspections_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspections_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          role: string
          status: string
          tenant_id: string
          token: string
        }
        Insert: {
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          role?: string
          status?: string
          tenant_id?: string
          token?: string
        }
        Update: {
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          role?: string
          status?: string
          tenant_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invitations_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      issues: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          inspection_id: string | null
          priority: string
          reported_at: string
          reported_by: string | null
          resolved_at: string | null
          source: string
          status: string
          tenant_id: string
          title: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
          work_order_id: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          inspection_id?: string | null
          priority?: string
          reported_at?: string
          reported_by?: string | null
          resolved_at?: string | null
          source?: string
          status?: string
          tenant_id?: string
          title: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
          work_order_id?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          inspection_id?: string | null
          priority?: string
          reported_at?: string
          reported_by?: string | null
          resolved_at?: string | null
          source?: string
          status?: string
          tenant_id?: string
          title?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
          work_order_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "issues_inspection_id_fkey"
            columns: ["inspection_id"]
            isOneToOne: false
            referencedRelation: "inspections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_work_order_id_fkey"
            columns: ["work_order_id"]
            isOneToOne: false
            referencedRelation: "work_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          full_name: string
          id: string
          language: string
          phone: string | null
          role: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          full_name?: string
          id: string
          language?: string
          phone?: string | null
          role?: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          language?: string
          phone?: string | null
          role?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      renewals: {
        Row: {
          amount: number | null
          completed_at: string | null
          created_at: string
          created_by: string | null
          due_date: string
          id: string
          name: string | null
          notes: string | null
          recurrence_months: number | null
          renewal_type: string
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          amount?: number | null
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          due_date: string
          id?: string
          name?: string | null
          notes?: string | null
          recurrence_months?: number | null
          renewal_type?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          amount?: number | null
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          due_date?: string
          id?: string
          name?: string | null
          notes?: string | null
          recurrence_months?: number | null
          renewal_type?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "renewals_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "renewals_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      service_reminders: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          due_date: string | null
          due_km: number | null
          id: string
          interval_km: number | null
          interval_months: number | null
          last_completed_at: string | null
          last_completed_km: number | null
          notes: string | null
          task: string
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          due_date?: string | null
          due_km?: number | null
          id?: string
          interval_km?: number | null
          interval_months?: number | null
          last_completed_at?: string | null
          last_completed_km?: number | null
          notes?: string | null
          task: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          due_date?: string | null
          due_km?: number | null
          id?: string
          interval_km?: number | null
          interval_months?: number | null
          last_completed_at?: string | null
          last_completed_km?: number | null
          notes?: string | null
          task?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_reminders_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_reminders_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      sl_devices: {
        Row: {
          created_at: string
          created_by: string | null
          current_vehicle_id: string | null
          firmware_version: string | null
          id: string
          imei: string | null
          manufacturer: string | null
          model: string | null
          notes: string | null
          purchase_date: string | null
          purchase_price: number | null
          serial: string
          status: string
          supplier: string | null
          tenant_id: string
          updated_at: string
          updated_by: string | null
          warranty_until: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          current_vehicle_id?: string | null
          firmware_version?: string | null
          id?: string
          imei?: string | null
          manufacturer?: string | null
          model?: string | null
          notes?: string | null
          purchase_date?: string | null
          purchase_price?: number | null
          serial: string
          status?: string
          supplier?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          warranty_until?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          current_vehicle_id?: string | null
          firmware_version?: string | null
          id?: string
          imei?: string | null
          manufacturer?: string | null
          model?: string | null
          notes?: string | null
          purchase_date?: string | null
          purchase_price?: number | null
          serial?: string
          status?: string
          supplier?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          warranty_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sl_devices_current_vehicle_id_fkey"
            columns: ["current_vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sl_devices_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      sl_jobs: {
        Row: {
          checklist: Json
          completed_at: string | null
          created_at: string
          created_by: string | null
          customer_id: string | null
          customer_signed: boolean
          device_id: string | null
          duration_minutes: number | null
          id: string
          job_type: string
          location: string | null
          notes: string | null
          number: number
          qc_at: string | null
          qc_by: string | null
          scheduled_date: string | null
          set_speed_kmh: number | null
          started_at: string | null
          status: string
          tamper_seal_number: string | null
          technician_id: string | null
          technician_signed: boolean
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          checklist?: Json
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          customer_signed?: boolean
          device_id?: string | null
          duration_minutes?: number | null
          id?: string
          job_type?: string
          location?: string | null
          notes?: string | null
          number: number
          qc_at?: string | null
          qc_by?: string | null
          scheduled_date?: string | null
          set_speed_kmh?: number | null
          started_at?: string | null
          status?: string
          tamper_seal_number?: string | null
          technician_id?: string | null
          technician_signed?: boolean
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          checklist?: Json
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          customer_signed?: boolean
          device_id?: string | null
          duration_minutes?: number | null
          id?: string
          job_type?: string
          location?: string | null
          notes?: string | null
          number?: number
          qc_at?: string | null
          qc_by?: string | null
          scheduled_date?: string | null
          set_speed_kmh?: number | null
          started_at?: string | null
          status?: string
          tamper_seal_number?: string | null
          technician_id?: string | null
          technician_signed?: boolean
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sl_jobs_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sl_jobs_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sl_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sl_jobs_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "sl_devices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sl_jobs_technician_id_fkey"
            columns: ["technician_id"]
            isOneToOne: false
            referencedRelation: "sl_technicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sl_jobs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sl_jobs_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      sl_settings: {
        Row: {
          cert_next_number: number
          cert_prefix: string
          cert_validity_months: number
          tenant_id: string
          updated_at: string
        }
        Insert: {
          cert_next_number?: number
          cert_prefix?: string
          cert_validity_months?: number
          tenant_id?: string
          updated_at?: string
        }
        Update: {
          cert_next_number?: number
          cert_prefix?: string
          cert_validity_months?: number
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sl_settings_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: true
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      sl_technicians: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          email: string | null
          id: string
          name: string
          phone: string | null
          tenant_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          email?: string | null
          id?: string
          name: string
          phone?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          email?: string | null
          id?: string
          name?: string
          phone?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sl_technicians_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      speed_limiter_certificates: {
        Row: {
          certificate_number: string
          created_at: string
          created_by: string | null
          customer_id: string | null
          device_id: string | null
          expires_at: string
          id: string
          installation_id: string | null
          issued_at: string
          issuing_authority: string | null
          job_id: string | null
          notes: string | null
          renewed_from: string | null
          revoked_at: string | null
          revoked_reason: string | null
          set_speed_kmh: number | null
          status: string
          tamper_seal_number: string | null
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          certificate_number: string
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          device_id?: string | null
          expires_at: string
          id?: string
          installation_id?: string | null
          issued_at?: string
          issuing_authority?: string | null
          job_id?: string | null
          notes?: string | null
          renewed_from?: string | null
          revoked_at?: string | null
          revoked_reason?: string | null
          set_speed_kmh?: number | null
          status?: string
          tamper_seal_number?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          certificate_number?: string
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          device_id?: string | null
          expires_at?: string
          id?: string
          installation_id?: string | null
          issued_at?: string
          issuing_authority?: string | null
          job_id?: string | null
          notes?: string | null
          renewed_from?: string | null
          revoked_at?: string | null
          revoked_reason?: string | null
          set_speed_kmh?: number | null
          status?: string
          tamper_seal_number?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "speed_limiter_certificates_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sl_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "sl_devices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_installation_id_fkey"
            columns: ["installation_id"]
            isOneToOne: false
            referencedRelation: "speed_limiter_installations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "sl_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_renewed_from_fkey"
            columns: ["renewed_from"]
            isOneToOne: false
            referencedRelation: "speed_limiter_certificates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_certificates_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      speed_limiter_installations: {
        Row: {
          brand: string | null
          created_at: string
          created_by: string | null
          customer_id: string | null
          device_id: string | null
          device_serial: string
          id: string
          installed_at: string
          job_id: string | null
          model: string | null
          notes: string | null
          set_speed_kmh: number | null
          status: string
          tamper_seal_number: string | null
          technician: string | null
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          brand?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          device_id?: string | null
          device_serial: string
          id?: string
          installed_at?: string
          job_id?: string | null
          model?: string | null
          notes?: string | null
          set_speed_kmh?: number | null
          status?: string
          tamper_seal_number?: string | null
          technician?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          brand?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          device_id?: string | null
          device_serial?: string
          id?: string
          installed_at?: string
          job_id?: string | null
          model?: string | null
          notes?: string | null
          set_speed_kmh?: number | null
          status?: string
          tamper_seal_number?: string | null
          technician?: string | null
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "speed_limiter_installations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_installations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sl_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_installations_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "sl_devices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_installations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "sl_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_installations_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speed_limiter_installations_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_modules: {
        Row: {
          enabled: boolean
          enabled_at: string
          enabled_by: string | null
          module_id: string
          tenant_id: string
        }
        Insert: {
          enabled?: boolean
          enabled_at?: string
          enabled_by?: string | null
          module_id: string
          tenant_id?: string
        }
        Update: {
          enabled?: boolean
          enabled_at?: string
          enabled_by?: string | null
          module_id?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_modules_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          address: string | null
          archetype: string
          country: string
          created_at: string
          currency: string
          distance_unit: string
          id: string
          name: string
          phone: string | null
          tax_registration_number: string | null
          timezone: string
          updated_at: string
          volume_unit: string
        }
        Insert: {
          address?: string | null
          archetype?: string
          country?: string
          created_at?: string
          currency?: string
          distance_unit?: string
          id?: string
          name: string
          phone?: string | null
          tax_registration_number?: string | null
          timezone?: string
          updated_at?: string
          volume_unit?: string
        }
        Update: {
          address?: string | null
          archetype?: string
          country?: string
          created_at?: string
          currency?: string
          distance_unit?: string
          id?: string
          name?: string
          phone?: string | null
          tax_registration_number?: string | null
          timezone?: string
          updated_at?: string
          volume_unit?: string
        }
        Relationships: []
      }
      vehicle_assignments: {
        Row: {
          created_at: string
          created_by: string | null
          driver_id: string
          ended_at: string | null
          id: string
          notes: string | null
          started_at: string
          tenant_id: string
          updated_by: string | null
          vehicle_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          driver_id: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          started_at?: string
          tenant_id?: string
          updated_by?: string | null
          vehicle_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          driver_id?: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          started_at?: string
          tenant_id?: string
          updated_by?: string | null
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vehicle_assignments_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicle_assignments_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicle_assignments_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      vehicles: {
        Row: {
          chassis_number: string | null
          created_at: string
          created_by: string | null
          customer_id: string | null
          engine_number: string | null
          fleet_number: string | null
          fuel_type: string
          id: string
          license_plate: string | null
          make: string | null
          model: string | null
          name: string
          notes: string | null
          odometer: number
          odometer_updated_at: string | null
          ownership: string
          purchase_date: string | null
          purchase_price: number | null
          status: string
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_type: string
          vin: string | null
          year: number | null
        }
        Insert: {
          chassis_number?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          engine_number?: string | null
          fleet_number?: string | null
          fuel_type?: string
          id?: string
          license_plate?: string | null
          make?: string | null
          model?: string | null
          name: string
          notes?: string | null
          odometer?: number
          odometer_updated_at?: string | null
          ownership?: string
          purchase_date?: string | null
          purchase_price?: number | null
          status?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_type?: string
          vin?: string | null
          year?: number | null
        }
        Update: {
          chassis_number?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string | null
          engine_number?: string | null
          fleet_number?: string | null
          fuel_type?: string
          id?: string
          license_plate?: string | null
          make?: string | null
          model?: string | null
          name?: string
          notes?: string | null
          odometer?: number
          odometer_updated_at?: string | null
          ownership?: string
          purchase_date?: string | null
          purchase_price?: number | null
          status?: string
          tenant_id?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_type?: string
          vin?: string | null
          year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "vehicles_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicles_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sl_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      work_order_lines: {
        Row: {
          category: string
          created_at: string
          created_by: string | null
          description: string
          id: string
          quantity: number
          tenant_id: string
          unit_cost: number
          updated_by: string | null
          work_order_id: string
        }
        Insert: {
          category?: string
          created_at?: string
          created_by?: string | null
          description: string
          id?: string
          quantity?: number
          tenant_id?: string
          unit_cost?: number
          updated_by?: string | null
          work_order_id: string
        }
        Update: {
          category?: string
          created_at?: string
          created_by?: string | null
          description?: string
          id?: string
          quantity?: number
          tenant_id?: string
          unit_cost?: number
          updated_by?: string | null
          work_order_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_order_lines_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_order_lines_work_order_id_fkey"
            columns: ["work_order_id"]
            isOneToOne: false
            referencedRelation: "work_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      work_orders: {
        Row: {
          completed_at: string | null
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          issue_id: string | null
          number: number
          odometer: number | null
          priority: string
          reminder_id: string | null
          scheduled_date: string | null
          status: string
          tax_rate: number
          tenant_id: string
          title: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
          vendor: string | null
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          issue_id?: string | null
          number: number
          odometer?: number | null
          priority?: string
          reminder_id?: string | null
          scheduled_date?: string | null
          status?: string
          tax_rate?: number
          tenant_id?: string
          title: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id: string
          vendor?: string | null
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          issue_id?: string | null
          number?: number
          odometer?: number | null
          priority?: string
          reminder_id?: string | null
          scheduled_date?: string | null
          status?: string
          tax_rate?: number
          tenant_id?: string
          title?: string
          updated_at?: string
          updated_by?: string | null
          vehicle_id?: string
          vendor?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "work_orders_issue_fk"
            columns: ["issue_id"]
            isOneToOne: false
            referencedRelation: "issues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_orders_reminder_id_fkey"
            columns: ["reminder_id"]
            isOneToOne: false
            referencedRelation: "service_reminders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_orders_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_orders_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      sl_contacts: {
        Row: {
          created_at: string | null
          customer_id: string | null
          department: string | null
          email: string | null
          id: string | null
          is_primary: boolean | null
          name: string | null
          notes: string | null
          phone: string | null
          tenant_id: string | null
          title: string | null
          updated_at: string | null
          whatsapp: string | null
        }
        Insert: {
          created_at?: string | null
          customer_id?: string | null
          department?: string | null
          email?: string | null
          id?: string | null
          is_primary?: boolean | null
          name?: string | null
          notes?: string | null
          phone?: string | null
          tenant_id?: string | null
          title?: string | null
          updated_at?: string | null
          whatsapp?: string | null
        }
        Update: {
          created_at?: string | null
          customer_id?: string | null
          department?: string | null
          email?: string | null
          id?: string | null
          is_primary?: boolean | null
          name?: string | null
          notes?: string | null
          phone?: string | null
          tenant_id?: string | null
          title?: string | null
          updated_at?: string | null
          whatsapp?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contacts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sl_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      sl_customers: {
        Row: {
          address: string | null
          billing_terms: string | null
          city: string | null
          country: string | null
          cr_number: string | null
          created_at: string | null
          credit_limit: number | null
          email: string | null
          id: string | null
          name: string | null
          notes: string | null
          phone: string | null
          status: string | null
          tax_number: string | null
          tenant_id: string | null
          updated_at: string | null
          website: string | null
        }
        Insert: {
          address?: string | null
          billing_terms?: string | null
          city?: string | null
          country?: string | null
          cr_number?: string | null
          created_at?: string | null
          credit_limit?: number | null
          email?: string | null
          id?: string | null
          name?: string | null
          notes?: string | null
          phone?: string | null
          status?: string | null
          tax_number?: string | null
          tenant_id?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Update: {
          address?: string | null
          billing_terms?: string | null
          city?: string | null
          country?: string | null
          cr_number?: string | null
          created_at?: string | null
          credit_limit?: number | null
          email?: string | null
          id?: string | null
          name?: string | null
          notes?: string | null
          phone?: string | null
          status?: string | null
          tax_number?: string | null
          tenant_id?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      complete_sl_job: {
        Args: {
          p_customer_signed?: boolean
          p_duration_minutes?: number
          p_job_id: string
          p_set_speed_kmh?: number
          p_tamper_seal_number?: string
          p_technician_signed?: boolean
        }
        Returns: undefined
      }
      fuel_summary: {
        Args: { p_vehicle_id?: string }
        Returns: {
          fill_count: number
          total_cost: number
          total_liters: number
        }[]
      }
      issue_certificate: {
        Args: {
          p_expires_at?: string
          p_issuing_authority?: string
          p_job_id: string
          p_notes?: string
        }
        Returns: {
          certificate_number: string
          created_at: string
          created_by: string | null
          customer_id: string | null
          device_id: string | null
          expires_at: string
          id: string
          installation_id: string | null
          issued_at: string
          issuing_authority: string | null
          job_id: string | null
          notes: string | null
          renewed_from: string | null
          revoked_at: string | null
          revoked_reason: string | null
          set_speed_kmh: number | null
          status: string
          tamper_seal_number: string | null
          tenant_id: string
          updated_at: string
          updated_by: string | null
          vehicle_id: string
        }
        SetofOptions: {
          from: "*"
          to: "speed_limiter_certificates"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      next_certificate_number: { Args: never; Returns: string }
      report_cost_by_vehicle: {
        Args: { p_from: string; p_ownership?: string; p_to: string }
        Returns: {
          fuel_cost: number
          maintenance_net: number
          maintenance_tax: number
          total_cost: number
          vehicle_id: string
          vehicle_name: string
        }[]
      }
      report_fuel_efficiency: {
        Args: { p_from: string; p_ownership?: string; p_to: string }
        Returns: {
          liters_per_100km: number
          pair_liters: number
          total_km: number
          total_liters: number
          vehicle_id: string
          vehicle_name: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
