export const enSlCertificates = {
  // List page
  "slCertificates.title": "Certificates",
  "slCertificates.description":
    "Speed limiter compliance certificates issued to your customers",
  "slCertificates.settings": "Certificate settings",
  "slCertificates.searchPlaceholder": "Search by number, customer, or vehicle…",

  // Filter chips
  "slCertificates.filterAll": "All",
  "slCertificates.filterValid": "Valid",
  "slCertificates.filter30": "≤ 30 days",
  "slCertificates.filter60": "31–60 days",
  "slCertificates.filter90": "61–90 days",
  "slCertificates.filterExpired": "Expired",
  "slCertificates.filterRevoked": "Revoked",

  // Table
  "slCertificates.number": "Certificate #",
  "slCertificates.customer": "Customer",
  "slCertificates.vehicle": "Vehicle",
  "slCertificates.issued": "Issued",
  "slCertificates.expires": "Expires",
  "slCertificates.expiresInDays": "Expires in {count} d",

  // Row actions
  "slCertificates.print": "Print",
  "slCertificates.copyVerifyLink": "Copy verify link",
  "slCertificates.linkCopied": "Link copied",
  "slCertificates.renew": "Renew",
  "slCertificates.revoke": "Revoke",

  // Renew modal
  "slCertificates.renewTitle": "Renew certificate",
  "slCertificates.renewLead": "Issue a new certificate replacing {number}.",
  "slCertificates.renewNumberHint":
    "The new certificate number is assigned automatically when issued.",
  "slCertificates.issuingAuthority": "Issuing authority",
  "slCertificates.setSpeed": "Set speed (km/h)",
  "slCertificates.issuedAt": "Issue date",
  "slCertificates.expiresAt": "Expiry date",
  "slCertificates.renewConfirm": "Issue certificate",
  "slCertificates.renewFailed": "Renewal failed",

  // Revoke modal
  "slCertificates.revokeTitle": "Revoke certificate",
  "slCertificates.revokeLead":
    "Certificate {number} will be marked as revoked and the public verification page will show it as revoked.",
  "slCertificates.revokeReason": "Reason",
  "slCertificates.revokeConfirm": "Revoke certificate",
  "slCertificates.revokeFailed": "Revoke failed",

  // Delete modal
  "slCertificates.deleteTitle": "Delete certificate",
  "slCertificates.deleteConfirm":
    "Delete certificate {number}? This cannot be undone.",
  "slCertificates.deleteFailed": "Delete failed",

  // Settings modal
  "slCertificates.settingsTitle": "Certificate settings",
  "slCertificates.certPrefix": "Certificate number prefix",
  "slCertificates.certPrefixHint":
    "Used when generating new certificate numbers, e.g. SLC.",
  "slCertificates.validityMonths": "Validity (months)",
  "slCertificates.validityHint":
    "Default validity period for new and renewed certificates.",
  "slCertificates.settingsSaveFailed": "Failed to save settings",

  // Empty states
  "slCertificates.emptyTitle": "No certificates yet",
  "slCertificates.emptyDesc":
    "Certificates are issued from completed jobs and will appear here.",
  "slCertificates.emptyFilteredTitle": "No matching certificates",
  "slCertificates.emptyFilteredDesc":
    "Try a different filter or search term.",

  // Print page
  "slCertificates.printTitle": "Speed Limiter Compliance Certificate",
  "slCertificates.certNumberLabel": "Certificate No.",
  "slCertificates.fieldCustomer": "Customer",
  "slCertificates.fieldVehicle": "Vehicle",
  "slCertificates.fieldPlate": "License plate",
  "slCertificates.fieldChassis": "Chassis number",
  "slCertificates.fieldDeviceSerial": "Device serial",
  "slCertificates.fieldSetSpeed": "Set speed",
  "slCertificates.fieldIssued": "Issue date",
  "slCertificates.fieldExpires": "Expiry date",
  "slCertificates.fieldAuthority": "Issuing authority",
  "slCertificates.scanToVerify": "Scan to verify",
  "slCertificates.authorizedSignature": "Authorized signature",
  "slCertificates.companyStamp": "Company stamp",
  "slCertificates.revokedBanner": "This certificate has been revoked",
  "slCertificates.revokedOn": "Revoked on {date}",
  "slCertificates.generatedBy": "Generated by FleetManage",
  "slCertificates.verifyAt": "Verify at:",
  "slCertificates.notFound": "Certificate not found",
} as const;
